# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M6MK72kesYgIciI3nXHPrJoyczDygj6I

Assignment Feedback Delay Analysis
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

print("⏳ System Status: Initializing Analysis Pipeline...")

# STEP 1: DATA INGESTION & MERGING

try:
    df_submission = pd.read_csv('studentAssessment.csv')
    df_assessments = pd.read_csv('assessments.csv')
    print("✅ Files Loaded Successfully.")
except FileNotFoundError:
    print("❌ ERROR: Files not found. Please upload 'studentAssessment.csv' and 'assessments.csv' to Colab.")
    df = pd.merge(df_submission, df_assessments, on='id_assessment', how='inner')

# STEP 2: DATA TRANSFORMATION (Dates)

course_start_date = pd.to_datetime('2024-01-01')
df['Submission_Date'] = course_start_date + pd.to_timedelta(df['date_submitted'], unit='D')

# STEP 3: REALISTIC SIMULATION (Data Augmentation)

unique_courses = df['code_module'].unique()
instructors_list = ['Prof. Sharma', 'Dr. Verma', 'Prof. Singh', 'Dr. Gupta', 'Prof. Lee', 'Dr. Patel', 'Prof. Das']

np.random.seed(42)
course_teacher_map = {course: np.random.choice(instructors_list) for course in unique_courses}
df['Instructor'] = df['code_module'].map(course_teacher_map)
random_delays = np.random.randint(1, 20, size=len(df))
df['Feedback_Date'] = df['Submission_Date'] + pd.to_timedelta(random_delays, unit='D')

#STEP 4: CORE CALCULATION (The "Delay" Metric)

df['Delay_Days'] = (df['Feedback_Date'] - df['Submission_Date']).dt.days

print(f"✅ Data Processed. Total Assignments Analyzed: {len(df)}")

#STEP 5: AGGREGATION & REPORTING

instructor_report = df.groupby('Instructor').agg(
    Total_Assignments=('id_assessment', 'count'),
    Avg_Delay=('Delay_Days', 'mean')
).sort_values(by='Total_Assignments', ascending=False).reset_index()

print("\n--- 📊 Generated Instructor Performance Report ---")
print(instructor_report)

#STEP 6: VISUALIZATION (Dashboard)

plt.figure(figsize=(16, 7))

plt.subplot(1, 2, 1)
sns.barplot(data=instructor_report, x='Instructor', y='Total_Assignments', palette='viridis')
plt.title('Instructor Workload Distribution', fontsize=14, fontweight='bold')
plt.xlabel('Instructor', fontsize=12)
plt.ylabel('Total Assignments Checked', fontsize=12)
plt.xticks(rotation=45)

plt.subplot(1, 2, 2)
sns.barplot(data=instructor_report, x='Instructor', y='Avg_Delay', palette='Reds')
plt.title('Feedback Efficiency (Average Delay in Days)', fontsize=14, fontweight='bold')
plt.xlabel('Instructor', fontsize=12)
plt.ylabel('Avg Delay (Days)', fontsize=12)
plt.xticks(rotation=45)

plt.axhline(y=10, color='blue', linestyle='--', label='Target SLA (10 Days)')
plt.legend()

plt.tight_layout()
plt.show()

busiest_instructor = instructor_report.iloc[0]['Instructor']
slowest_instructor = instructor_report.sort_values(by='Avg_Delay', ascending=False).iloc[0]['Instructor']

print("\n" + "="*50)
print("🚀 FINAL EXECUTIVE SUMMARY")
print("="*50)
print(f"1. WORKLOAD: {busiest_instructor} handled the highest volume of assignments.")
print(f"2. BOTTLENECK: {slowest_instructor} had the longest average feedback delay.")
print("3. RECOMMENDATION: Reallocate resources from low-workload instructors to reduce delays.")

